defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_
 
scheduler:
  decay_rate: 0.95
  decay_steps: 2000

training:
  rec_results_freq : 1000
  rec_constraint_freq: 10000000
  max_steps : 2000000

batch_size:
  inlet: 160
  outlet: 160
  walls: 160
  no_slip: 320
  interior: 3200

